sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t smileajw1004/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true smileajw1004/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk #외부 서비스 표시(firebase)
  region: "ap-northeast-2" #aws 장소
  app: "docker-react-app" #어플리케이션 이름
  env: "Docker-react-app-env" #환경이름
  bucket_name: "elasticbeanstalk-ap-northeast-2-002502774475" #elasticbeanstalk을 위한 S3 버켓 이름(aws의 저장소 역할)
  bucket_path: "docker-react-app"
  on:
    branch: master

  #travis_CI와 AWS가 연동하기 위한 설정
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY